name: Netcat Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # Updated to the latest version

      - name: wait for IRC to start
        run: "sleep 10"

      - name: op IRC client
        run: "nc localhost 8000 < tests/test.txt > logs/out_client.log 2> logs/out_client_err.log &"

      - name: non-op IRC client
        run: "nc localhost 8000 < tests/test2.txt > logs/out_client2.log 2> logs/out_client_err2.log &"


      - name: kill IRC
        run: "killall ircserv || true" # Prevents the workflow from failing if ircserv is not found

      - name: Upload log files
        uses: actions/upload-artifact@v4  # Ensure this is the latest version
        with:
          name: irc-logs
          path: logs/